### ISSUE TITLE
[FEATURE] Sorting downloaded files from the Imgbox website.

### ISSUE THREAD

**Issue by D0n-A** [jbsparrow/CyberDropDownloader#223]
Hello! There is the following problem / improvement request: when downloading files from the Imgbox website, they are saved without certain sorting as on the site of the same name.

Description:
1. Let's download a random [example](https://imgbox.com/g/BR1rPtvClU) - photo gallery with a certain order of files;
2. Add it as usual to the grabber on the standard settings;
3. The download will be successful; but the sorting already will be done by Windows Explorer (00x8qD0x_o.jpg will be displayed first, the second one is 0auhCDxN_o.jpg, etc.) - and it will not correspond the desired sorting;
4. Grabber Setup: `sort_downloads`and others - also had no effect.

Solution:
Unfortunately, I don't have a specific offer on this issue, but have the following remark: if you inspect a single image, it will have a "title" property, for example, in the first image:
`<img alt="5dsxr4vp o" class="image-content" id="img" onclick="rs()" src="https://images2.imgbox.com/be/16/5DSXR4VP_o.jpg" title="JCA_x_CEA_CC-Small-1.jpg">`

Hence, it would be great if the user somehow had a choice when saving by the “title” property, or “by the standard” (as is already done now).

Additional context:
I have already left a similar [request](https://github.com/Jules-WinnfieldX/CyberDropDownloader/issues/758) before in the old repository, but the author left it completely unattended. 
The site, of course, is not very popular, but some will find this useful.
Thank you!

**Comment by jbsparrow** [comment]
Sort_downloads moves the downloads to the folder specified in the config. I can definitely set the file name to the title though. It should have functioned like that originally.

**Comment by jbsparrow** [comment]
I took a look at what you mean. You want the titles seen when you open the full image to be the filename. 

This is possible but it's problematic, it would require us to double the amount of requests.

The example album you sent has 340 images. We make 1 request to get the gallery which has all of the images' thumbnail file locations. With that, we are able to determine the url of the full quality file on their API.

So for an album of size `n=340`, we would make `n+1` (341) requests with the current system.

If we are saving the filenames, we have to make two requests, one for each images main page in order to fetch the title, plus another to download the file. Giving us `2n+1` (681) requests.

Unfortunately, that doesn't seem viable. That would put a lot of extra load on their website and thus it isn't something I feel comfortable implementing into CDL.

I imagine you could fairly easily make your own script to accomplish that if you wanted to.
