### ISSUE TITLE
[BUG]Cannot save content items with no date in nekohouse

### ISSUE THREAD

**Issue by mikashina** [jbsparrow/CyberDropDownloader#256]
I am unable to save a post that has no date in nekohouse.

Is it possible to fix this bug? The content URL itself is there and I would like it to be saved.

ex: https://nekohouse.su/fantia_products/user/19729

**Comment by lattaai5** [comment]
Hello, I tried to fix the issue

This is what I did:

Modified the `handle_post_content` method in the `NekohouseCrawler` class to use a default date when the post's published date is not available. This allows the scraper to save posts even when they don't have a date, fixing the issue with saving posts from URLs like https://nekohouse.su/fantia_products/user/19729.

I also created pull request: https://github.com/jbsparrow/CyberDropDownloader/pull/257


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
